package com.chin.domain.usecase

interface UseCaseNotification

class InternalErrorNotification: UseCaseNotification
class AddressNotFoundNotification: UseCaseNotification
class NetworkErrorNotification: UseCaseNotification